from setuptools import setup, Extension

raptoreum_hash_module = Extension('raptoreum_hash',
                                 sources = ['raptoreummodule.c',
                                            'ghostrider.c',
                                            'sha3/sph_blake.c',
                                            'sha3/sph_bmw.c',
                                            'sha3/sph_groestl.c',
                                            'sha3/sph_jh.c',
                                            'sha3/sph_keccak.c',
                                            'sha3/sph_skein.c',
                                            'sha3/sph_luffa.c',
                                            'sha3/sph_cubehash.c',
                                            'sha3/sph_shavite.c',
                                            'sha3/sph_simd.c',
                                            'sha3/sph_echo.c',
                                            'sha3/sph_hamsi.c',
                                            'sha3/sph_fugue.c',
                                            'sha3/sph_shabal.c',
                                            'sha3/sph_whirlpool.c',
                                            'sha3/sph_sha2.c',
                                            'sha3/sph_tiger.c',
                                            'sha3/sph_haval.c',
                                            'Lyra2.c',
                                            'Sponge.c',
                                            'gost.c',
                                            'cryptonote/cryptonight_dark.c',
                                            'cryptonote/cryptonight_dark_lite.c',
                                            'cryptonote/cryptonight_fast.c',
                                            'cryptonote/cryptonight.c',
                                            'cryptonote/cryptonight_lite.c',
                                            'cryptonote/cryptonight_soft_shell.c',
                                            'cryptonote/cryptonight_turtle.c',
                                            'cryptonote/cryptonight_turtle_lite.c',
                                            'cryptonote/crypto/aesb.c',
                                            'cryptonote/crypto/oaes_lib.c',
                                            'cryptonote/crypto/c_keccak.c',
                                            'cryptonote/crypto/c_groestl.c',
                                            'cryptonote/crypto/c_blake256.c',
                                            'cryptonote/crypto/c_jh.c',
                                            'cryptonote/crypto/c_skein.c',
                                            'cryptonote/crypto/hash.c',
                                            'cryptonote/crypto/wild_keccak.cpp',],
                               include_dirs=['.', './sha3','/cryptonote','/cryptonote/crypto'])

setup (name = 'raptoreum_hash',
       version = '1.0.0',
       description = 'Binding for Raptoreum Ghostrider proof of work hashing.',
       ext_modules = [raptoreum_hash_module])
